name: Release Python package with pontos

on:
  pull_request:
    types: [closed]

jobs:
  build-and-release:
    env:
      GITHUB_USER: ${{ secrets.GREENBONE_BOT }}
      GITHUB_TOKEN: ${{ secrets.GREENBONE_BOT_TOKEN }}
      SIGNING_KEY: ${{ secrets.GREENBONE_BOT_SIGNING_KEY }}
    name: Build and release with pontos
    # If the label 'make release' is set
    # If PR is closed because of an merge
    if: contains( github.event.pull_request.labels.*.name, 'make release') && github.event.pull_request.merged == true
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
    - name: Prepare release with pontos
      run: |
        poetry run pontos-release prepare --calendar
    - name: Release with pontos
      run: |
        poetry run pontos-release release
